In [ ]:
from sklearn.mixture import GaussianMixture
import numpy as np
from scipy.stats import norm, binom

pi1, mu1, s1, mu2, s2 = 0.25, 0, 1, 3, 1
n = 100
N = 100
Params = np.zeros((N, 6)) # store the estimated parameters
for i in range(N):
    n1 = binom.rvs(n, pi1)
    n2 = n - n1
    x1 = norm.rvs(loc=mu1, scale=s1, size=n1)
    x2 = norm.rvs(loc=mu2, scale=s2, size=n2)
    sample = np.concatenate((x1, x2)).reshape(-1, 1) # must be a column vector

    gmm = GaussianMixture(n_components=2, covariance_type='full', \
                            weights_init=[pi1, 1-pi1], \
                            means_init=np.array([mu1, mu2]).reshape(2, 1),\
                            max_iter = 1000, tol = 1e-6)
    gmm.fit(sample) # sample is the normal mixture data as a column vector
    Params[i, :] = np.concatenate((gmm.weights_, gmm.means_.flatten(), \
                            gmm.covariances_.flatten()))

print(Params)
# print(gmm.weights_)
# print(gmm.means_)
# print(gmm.covariances_)
# # print the estimated parameters
# print('pi:', gmm.weights_[0])
# print('mu1:', gmm.means_[0])
# print('mu2:', gmm.means_[1])
# print('s1:', gmm.covariances_[0])
# print('s2:', gmm.covariances_[1])

[[ 0.28672297  0.71327703  0.06465714  3.01088007  0.78833087  0.89746342]
 [ 0.38615957  0.61384043  0.99632868  3.11992267  0.94679871  0.83986401]
 [ 0.09388108  0.90611892 -0.60055423  2.3493539   0.09803506  1.4976613 ]
 [ 0.25250789  0.74749211  0.55324875  3.17368625  1.62576961  0.86344523]
 [ 0.11006038  0.88993962 -0.50881417  2.8549218   0.46131238  1.46844658]
 [ 0.32897173  0.67102827  0.37707995  3.17434604  1.1063624   0.6881107 ]
 [ 0.10753037  0.89246963 -0.74362566  2.83040211  0.42121298  0.94343645]
 [ 0.20470883  0.79529117 -0.60600734  2.66655556  0.7200476   1.34026358]
 [ 0.28572112  0.71427888  0.21189013  2.81627658  1.30308728  0.91141486]
 [ 0.19570552  0.80429448 -0.31720949  3.02269796  0.91798206  1.18998768]
 [ 0.18283408  0.81716592 -0.35973328  2.85494586  0.26307136  1.55791272]
 [ 0.22507938  0.77492062 -0.49962484  3.06368732  0.42646076  1.38104052]
 [ 0.26972732  0.73027268 -0.13351282  3.05377948  1.37325294  0.61684347]
 [ 0.30994168  0.69005832